#!/bin/bash
# Single entry point + lifecycle control for the cockpit.
#
#   ./tui.sh              attach to the running TUI, or start one and attach
#   ./tui.sh start        start detached; clears the autostart hold
#   ./tui.sh stop         quit + HOLD — autostart will NOT resurrect it
#   ./tui.sh restart      stop + start detached — picks up edited code
#   ./tui.sh status       session / pane-pid / clients / autostart / hold
#   ./tui.sh attach       attach only — fails if nothing is running
#   ./tui.sh autostart on|off
#                         always-on via launchd: start at login, self-heal
#                         within 5 min if the TUI dies
#
# Always-on rules (while autostart is ON):
#   reboot / login   -> cockpit starts detached automatically
#   crash or 'q'     -> revived within <=5 min ('q' = restart the app)
#   ./tui.sh stop    -> hold set — stays down until ./tui.sh [start]
#
# This + the flock guard in tui.py means there is always exactly ONE live
# instance — no more buys typed into a forgotten window running old code.
# Detach without quitting: Ctrl-b then d.   Quit the app: q.
cd "$(dirname "$0")" || exit 1

SESSION="alpaca_tui"
CMD="venv/bin/python3 tui.py"
STATE_DIR="$HOME/.local/state/alpaca_tui"
HOLD="$STATE_DIR/hold"
LAUNCHER="$HOME/.local/bin/alpaca-tui-autostart"
LABEL="com.alpacapapertrader.tui"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"

alive() {  # session exists AND has a live (non-dead) pane
  tmux has-session -t "$SESSION" 2>/dev/null &&
    tmux list-panes -t "$SESSION" -F '#{pane_dead}' | grep -q '^0$'
}

reap() {   # clear dead-pane sessions + launcher processes orphaned by a
           # tmux-server restart (their socket got clobbered; they linger
           # in ps and look running when nothing is)
  if tmux has-session -t "$SESSION" 2>/dev/null && ! alive; then
    tmux kill-session -t "$SESSION"
  fi
  alive || pkill -f "tmux new-session -A -s $SESSION" 2>/dev/null
}

autostart_loaded() {
  launchctl print "gui/$(id -u)/$LABEL" >/dev/null 2>&1
}

start_detached() {
  rm -f "$HOLD"
  if alive; then
    echo "already running — ./tui.sh to attach"
    return 0
  fi
  reap
  tmux new-session -d -s "$SESSION" "$CMD"
  sleep 1
  if alive; then
    echo "started (detached) — ./tui.sh to attach"
  else
    echo "FAILED to start — pane died immediately; run '$CMD' directly to see the error" >&2
    return 1
  fi
}

stop_it() {
  mkdir -p "$STATE_DIR"
  touch "$HOLD"
  autostart_loaded && echo "hold set — autostart will not restart it (./tui.sh start clears)"
  if ! alive; then
    reap
    echo "not running"
    return 0
  fi
  tmux send-keys -t "$SESSION" q   # graceful: same as pressing q in the app
  for _ in 1 2 3 4 5 6 7 8 9 10; do
    alive || break
    sleep 0.5
  done
  if alive; then
    tmux kill-session -t "$SESSION"
    echo "stopped (forced — 'q' didn't exit within 5s)"
  else
    tmux kill-session -t "$SESSION" 2>/dev/null   # discard the dead-pane shell
    echo "stopped"
  fi
}

status_it() {
  if alive; then
    pane_pid=$(tmux list-panes -t "$SESSION" -F '#{pane_pid}' | head -1)
    clients=$(tmux list-clients -t "$SESSION" 2>/dev/null | wc -l | tr -d ' ')
    echo "running — session $SESSION · pane pid $pane_pid · $clients client(s) attached"
  else
    echo "not running"
    pgrep -f "tmux new-session -A -s $SESSION" >/dev/null 2>&1 &&
      echo "  (stale launcher process present — 'stop' or 'restart' will reap it)"
  fi
  if autostart_loaded; then
    echo "autostart: ON — starts at login, self-heals within 5 min ($LABEL)"
  else
    echo "autostart: OFF — ./tui.sh autostart on to enable"
  fi
  [ -f "$HOLD" ] && echo "hold: SET — autostart paused until ./tui.sh [start]"
  return 0
}

autostart_on() {
  mkdir -p "$STATE_DIR" "$HOME/.local/bin" "$HOME/Library/LaunchAgents"
  TMUX_BIN="$(command -v tmux)" || { echo "tmux not found" >&2; return 1; }

  # Launcher lives OUTSIDE Desktop: launchd's bash must never touch a
  # TCC-protected path (that's what kills jobs at spawn with exit 78).
  # Only the tmux pane enters the repo, under the tmux server's identity.
  cat > "$LAUNCHER" <<EOF
#!/bin/bash
# launchd autostart guard for the Alpaca TUI cockpit.
# Generated by tui.sh 'autostart on' — do not edit by hand.
TMUX="$TMUX_BIN"
REPO="$PWD"
SESSION="$SESSION"
HOLD="\$HOME/.local/state/alpaca_tui/hold"

[ -f "\$HOLD" ] && exit 0                       # intentional stop — stay down
if "\$TMUX" has-session -t "\$SESSION" 2>/dev/null; then
  "\$TMUX" list-panes -t "\$SESSION" -F '#{pane_dead}' | grep -q '^0\$' && exit 0
  "\$TMUX" kill-session -t "\$SESSION"          # reap dead-pane session
fi
exec "\$TMUX" new-session -d -s "\$SESSION" -c "\$REPO" "venv/bin/python3 tui.py"
EOF
  chmod +x "$LAUNCHER"

  cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$LAUNCHER</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>StartInterval</key><integer>300</integer>
  <key>StandardOutPath</key><string>$STATE_DIR/launchd.log</string>
  <key>StandardErrorPath</key><string>$STATE_DIR/launchd.log</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key><string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
  </dict>
</dict>
</plist>
EOF

  launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null
  if launchctl bootstrap "gui/$(id -u)" "$PLIST"; then
    echo "autostart ON — cockpit starts at login and self-heals within 5 min"
  else
    echo "autostart install FAILED (launchctl bootstrap)" >&2
    return 1
  fi
}

autostart_off() {
  if launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null; then
    echo "autostart OFF — cockpit no longer starts at login"
  else
    echo "autostart was not loaded"
  fi
}

case "${1:-}" in
  start)   start_detached ;;
  stop)    stop_it ;;
  restart) stop_it; start_detached ;;
  status)  status_it ;;
  attach)
    alive || { echo "not running — use ./tui.sh start" >&2; exit 1; }
    exec tmux attach-session -t "$SESSION"
    ;;
  autostart)
    case "${2:-}" in
      on)  autostart_on ;;
      off) autostart_off ;;
      *)   echo "usage: $0 autostart on|off" >&2; exit 2 ;;
    esac
    ;;
  "")
    # Historic default: attach if running, else start fresh and attach.
    rm -f "$HOLD"
    reap
    exec tmux new-session -A -s "$SESSION" "$CMD"
    ;;
  *)
    echo "usage: $0 [start|stop|restart|status|attach|autostart on|off]" >&2
    exit 2
    ;;
esac
